import streamlit as st

# Page configuration
st.set_page_config(
    page_title="Credentials System - KPMG",
    page_icon="📊",
    layout="wide",
    initial_sidebar_state="expanded"
)

# Main landing page
st.title("📊 KPMG Credentials Management System")
st.markdown("---")

st.markdown("""
## Welcome to the Credentials System

This application provides powerful tools for managing and presenting KPMG project credentials.

### Available Features

Use the **sidebar** to navigate between different pages:

#### 📁 **Project Database** (Page 4)
- **AI-powered conversational search** for natural language queries
- Browse and filter projects by industry, partner, manager, year
- Export data to CSV or Excel
- Multi-turn dialogue with context memory
- *Password protected* (password: bud123)

#### 🔍 **Credential Browser** (Page 5)
- Fast, non-AI search and filtering
- Search by person name (partners/managers)
- Filter by year, industry, sector, client
- Quick export functionality
- *Password protected* (password: bud123)

#### 📝 **PowerPoint Generator** (Page 6)
- **AI chat agent** for creating credential presentations
- Natural language requests: "I want the most recent experience of [person] filled in"
- Automatic project selection (sorts by year, AI selects for diversity)
- Dynamic project descriptions generated by AI
- Natural language filtering ("Only 2024-2025 projects", "financial services only")
- Downloads ready-to-use PowerPoint presentations
- *Password protected* (password: bud123)

### Getting Started

1. **Navigate** using the sidebar on the left
2. **Enter password**: bud123 (when prompted)
3. **Choose your tool**:
   - Need to query projects? → **Project Database**
   - Need to browse quickly? → **Credential Browser**
   - Need to create presentations? → **PowerPoint Generator**

### AI Features

This system includes **TWO AI chat agents**:
- **Project Database**: Ask questions about projects in natural language
- **PowerPoint Generator**: Request credential presentations conversationally

*Note: AI features require KPMG network access (VPN or on-premises)*

---

**👈 Select a page from the sidebar to begin!**
""")

# Add some helpful tips
with st.expander("💡 Quick Tips"):
    st.markdown("""
    - **All pages are password protected** with the same password: `bud123`
    - **AI Chat works best locally** - requires KPMG network access
    - **Export features** are available on all pages (CSV/Excel)
    - **PowerPoint Generator** uses AI to create professional descriptions
    - **Project selection** is smart - sorts by year and ensures project diversity
    - **Natural language** works for filtering: "Only 2024-2025 projects", "financial services only"
    """)

with st.expander("🔧 Technical Information"):
    st.markdown("""
    **Database**: credentials_full.xlsx (114 projects, 38 columns)
    
    **Template**: Bud van der Schier– Partner.pptx
    
    **AI Model**: GPT-4 (gpt-4o-2024-08-06-dzs-we) via KPMG Workbench API
    
    **Features**:
    - Multi-page Streamlit architecture
    - Conversational AI with context memory
    - Dynamic description generation
    - Smart project selection algorithms
    - Excel and CSV export capabilities
    """)

# Footer
st.markdown("---")
st.caption("KPMG Credentials Management System | Powered by Streamlit & GPT-4")
