"""
Credentials Management System - Download Page

Download the complete credentials system to run locally with AI features.
"""

import streamlit as st

st.set_page_config(
    page_title="Credentials System - Download",
    page_icon="📥",
    layout="wide"
)

st.title("📥 Credentials Management System")
st.markdown("---")

st.markdown("""
## 🎯 Complete Credentials System with AI

The **Credentials Management System** is a powerful tool for managing and generating KPMG project credentials presentations.
Due to KPMG API requirements, this system needs to run **locally** on your machine.

### 🌟 What's Included

The downloadable package includes **three powerful AI-driven tools**:

#### 1️⃣ **Project Database with AI Chat** 📊
- **Conversational AI interface** for natural language queries
- Ask questions like: *"Show me all projects in technology"* or *"Find projects by Tim Kramer"*
- Browse and filter by industry, partner, manager, year
- Multi-turn dialogue with context memory
- Export to CSV or Excel
- Password protected (bud123)

#### 2️⃣ **Credential Browser** 🔍
- Fast, non-AI search and filtering
- Search by person name (partners/managers)
- Filter by year, industry, sector, client
- Quick export functionality
- Password protected (bud123)

#### 3️⃣ **PowerPoint Generator with AI Chat** 📝
- **AI chat agent** for creating credential presentations
- Natural language requests: *"Fill in the template with Bud van der Schier's most recent experience"*
- Automatic project selection (sorts by year, AI selects for diversity)
- Dynamic project descriptions generated by AI
- Natural language filtering: *"Only 2024-2025 projects"*, *"financial services only"*
- Downloads ready-to-use PowerPoint presentations
- Password protected (bud123)

---

## 💻 System Requirements

- **Windows PC** (with PowerShell)
- **KPMG network access** (VPN or on-premises) for AI features
- **Python 3.8+** with Streamlit, pandas, openpyxl, plotly, requests, python-pptx
- **Database**: credentials_full.xlsx (included)
- **Template**: Bud van der Schier– Partner.pptx (included)

---

## 📥 Download Options

### Option 1: Complete Repository (Recommended)
""")

# GitHub download button
github_repo = "martinomartini/room_allocator_strategy_2"
download_url = f"https://github.com/{github_repo}/archive/refs/heads/main.zip"

st.link_button(
    "⬇️ Download Complete Repository from GitHub",
    download_url,
    type="primary",
    use_container_width=True
)

st.markdown("""
**After downloading:**
1. Extract the ZIP file
2. Navigate to the `standalone/` folder
3. Double-click `Launch.bat`
4. Browser opens automatically with all features!
5. Enter password: **bud123**

---

### Option 2: Direct Clone (For Git Users)

```bash
git clone https://github.com/martinomartini/room_allocator_strategy_2.git
cd room_allocator_strategy_2/standalone
# Double-click Launch.bat or run:
.\Launch.bat
```

---

## 🚀 Quick Start Guide

1. **Extract Files**: Unzip the downloaded package
2. **Open Standalone Folder**: Navigate to `room_allocator_strategy_2/standalone/`
3. **Launch Application**: Double-click `Launch.bat`
4. **Enter Password**: Use **bud123** when prompted
5. **Navigate Pages**: Use sidebar to switch between:
   - 📊 Project Database (AI chat)
   - 🔍 Credential Browser (fast search)
   - 📝 PowerPoint Generator (AI chat)

---

## 🔧 Installation (If Python Not Installed)

If you don't have Python installed:

```bash
# Install Python from python.org
# Then install required packages:
pip install streamlit pandas openpyxl plotly requests python-pptx
```

Or use the requirements.txt in the standalone folder:
```bash
cd standalone
pip install -r requirements.txt
```

---

## 💡 Key Features

### AI-Powered Project Selection
- **Smart sorting**: Prioritizes recent projects (by year)
- **Diversity selection**: AI picks projects from different sectors/industries
- **Natural language filtering**: *"Only financial services projects from 2024-2025"*

### Dynamic Descriptions
- **AI-generated descriptions**: Creates concise, professional project summaries
- **Customizable detail level**: Choose between full descriptions or concise format
- **Professional formatting**: Clean PowerPoint output ready for presentations

### Multi-Turn Conversations
- **Context memory**: Both AI agents remember conversation history
- **Follow-up questions**: Ask clarifying questions naturally
- **Interactive workflow**: Guided process for PowerPoint generation

---

## 📋 Sample Queries

### Project Database AI Chat:
- *"Show me all projects in the paper industry"*
- *"Find all projects by Tim Kramer"*
- *"Projects from 2025 in technology sector"*
- *"Give me all financial services projects"*

### PowerPoint Generator AI Chat:
- *"Fill in the template with Bud van der Schier's most recent experience"*
- *"Generate credentials for Tim Kramer"*
- *"Create a presentation for Charbel Moussa"*
- *"I need Harold de Bruijn's latest project credentials"*

### Natural Language Filters:
- *"Only 2024-2025 projects"*
- *"Financial services only"*
- *"Exclude audit projects"*
- *"Projects in healthcare or technology"*

---

## 🔐 Security

- All three tools are **password protected** (password: **bud123**)
- Runs completely **locally** on your machine
- **No cloud data transmission** - all processing happens on your PC
- **KPMG API** requires network access (VPN or on-premises)

---

## 🆘 Troubleshooting

### AI Features Not Working?
- ✅ Ensure you're connected to **KPMG VPN** or on-premises network
- ✅ Check that the **API key** is configured (default is pre-filled)
- ✅ Verify **Python packages** are installed: `pip install -r requirements.txt`

### Application Won't Start?
- ✅ Ensure **Python 3.8+** is installed
- ✅ Check that **port 8501** is not in use
- ✅ Run from PowerShell: `streamlit run app.py`

### Files Not Found?
- ✅ Ensure you're running `Launch.bat` from the **standalone/** folder
- ✅ Verify **credentials_full.xlsx** and **template.pptx** are present
- ✅ Check file permissions

---

## 📞 Support

For issues or questions:
1. Check the **README.md** in the standalone folder
2. Review **CREDENTIALS_MANAGER_INTEGRATION.md** for technical details
3. Contact the system administrator

---

## 🎓 Learn More

- **AI Chat Agents**: Both Project Database and PowerPoint Generator use GPT-4 for natural language understanding
- **Smart Selection**: Algorithm combines recency (year sorting) with diversity (AI-powered selection)
- **Professional Output**: Generated PowerPoints use clean formatting matching KPMG standards

---

**Ready to get started?** Download the package above and run `Launch.bat`! 🚀
""")

# Footer
st.markdown("---")
st.caption("KPMG Credentials Management System | Requires KPMG Network Access for AI Features")
